# Generated by Django 4.1.1 on 2022-10-04 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='timelog',
            options={'ordering': ['-date'], 'verbose_name_plural': 'timelogs'},
        ),
    ]
