# Generated by Django 4.1.1 on 2022-10-04 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0002_alter_activity_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='log_time',
            field=models.DurationField(default='00:30:00'),
        ),
    ]
