# Generated by Django 4.1.1 on 2022-10-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0003_alter_timelog_date_alter_timelog_log_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='log_time',
            field=models.DurationField(),
        ),
    ]
