# Generated by Django 4.1.1 on 2022-10-04 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0004_alter_timelog_log_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(default='activity name', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default='category description', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='category name', max_length=30),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='log_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
