# Generated by Django 4.1.1 on 2022-10-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0005_alter_activity_name_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='category name', max_length=30, unique=True),
        ),
    ]
