# Generated by Django 4.1.1 on 2022-10-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='color',
            field=models.CharField(choices=[('gray', 'gray'), ('yellow', 'yellow'), ('purple', 'purple'), ('orange', 'orange'), ('blue', 'blue'), ('green', 'green'), ('pink', 'pink')], default='gray', max_length=100),
        ),
    ]
