# Generated by Django 4.1.1 on 2022-10-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0007_alter_activity_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='color',
            field=models.CharField(choices=[('gray', 'gray'), ('yellow', 'yellow'), ('purple', 'purple'), ('orange', 'orange'), ('blue', 'blue'), ('green', 'green'), ('black', 'black')], default='gray', max_length=100),
        ),
    ]
